export const IMAGE_URL = 'asset';
export const FINGERPRINT_SIZE = 35
export const TOTAL_NUMBER_SIZE = 4;
export const CHUNK_NUMBER_SIZE = 4;
export const HEADER_SIZE_IN_BYTES = FINGERPRINT_SIZE + TOTAL_NUMBER_SIZE + CHUNK_NUMBER_SIZE;
