export const ADD_PEER = "ADD_PEER";
export const DELETE_PEER = "DELETE_PEER";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const UPDATE_MY_UUID = "UPDATE_MY_UUID";
export const UPDATE_PEER_UUID = "UPDATE_PEER_UUID";
export const ADD_FILES = "ADD_FILES";
export const DELETE_FILES = "DELETE_FILES";
export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
export const UPDATE_IS_SYSTEM_MESSAGE_SELECTED =
    "UPDATE_IS_SYSTEM_MESSAGE_SELECTED";
export const ADD_SYSTEM_MESSAGE = "ADD_SYSTEM_MESSAGE";
export const UPDATE_SELECTED_PEER = "UPDATE_SELECTED_PEER";
